function handles = Image(model)
%VIEW  a GUI representation of the TCSPCImageData model

% Build GUI
handles = initGUI();

% Initial update
onModelChanged(handles, model);

% Observe model changes and update view accordingly
addlistener(model, 'isdirty', 'PostSet', ...
    @(o,e) onModelChanged(handles,e.AffectedObject));

end

function handles = initGUI()
% Gets the px coordinates delimiting screen area as:
% Left Bottom Width Height
scrsz = get(groot,'ScreenSize');

hFig = figure(...
    'Menubar','none', ...
    'Position',[scrsz(3)/4  scrsz(4) / 4 scrsz(3)/2 scrsz(3)/2], ...
    'Name', 'Image', ...
    'NumberTitle', 'off');

% Master panel
hPanel = uix.Panel('Parent', hFig, ...
    'Padding', 20);
% Master panel is divided in a 1 column grid with multple lines of
% controls.
hGrid = uix.Grid('Parent', hPanel, ...
    'Spacing', 20);

% First the axes.
hAxes = axes('Parent', uicontainer('Parent', hGrid));
axis square;

% Next, a row of buttons and labels.
hBox2 = uix.HBox('Parent', hGrid);

hGridGate = uix.Grid('Parent', hBox2, ...
    'Spacing', 5);

hLblgmin = uicontrol('Parent', hGridGate, ...
    'Style', 'text', ...
    'String', 'Min gate (ns)');

hLblgmax = uicontrol('Parent', hGridGate, ...
    'Style', 'text', ...
    'String', 'Max gate (ns)');

hEdtgmin = uicontrol('Parent', hGridGate, ...
    'Style', 'edit', ...
    'String', '0');

hEdtgmax = uicontrol('Parent', hGridGate, ...
    'Style', 'edit', ...
    'String', '100');

hBtnApply = uicontrol('Parent', hGridGate, ...
    'Style', 'pushbutton', ...
    'String', 'Apply');

uix.Empty( 'Parent', hGridGate )

set(hGridGate, 'Widths', [ -1 -1 -1 ], 'Heights', [ -1 -1 ]);

hBox3 = uix.HBox('Parent', hGrid);

set(hGrid, 'Widths', [ -1 ], 'Heights', [ -1 -0.05 -0.05 ]);

hBtnup = uicontrol('Parent', hBox3, ...
    'Style', 'pushbutton', ...
    'String', 'Previous');

hLblfr = uicontrol('Parent', hBox3, ...
    'Style', 'text', ...
    'String', 'Frame 1');

hBtndwn = uicontrol('Parent', hBox3, ...
    'Style', 'pushbutton', ...
    'String', 'Next');

handles = struct( ...
'fig', hFig, ...
'axes', hAxes, ...
'edtgmin', hEdtgmin, ...
'edtgmax', hEdtgmax, ...
'btnapply', hBtnApply, ...
'btnup', hBtnup, ...
'lblfr', hLblfr, ...
'btndwn', hBtndwn);

end

function onModelChanged(handles, model)
    set(handles.fig, 'CurrentAxes', handles.axes);
    imagesc(model.render());
    colorbar(handles.axes);
    set(handles.lblfr, 'String', model.frame);
end