classdef Image < handle
    %IMAGE The Image View.
    %   TODO: Add.
    
    properties
        handles
        model
    end
    
    methods
        
        function obj = Image(model)
            
            obj.model = model;
            
            % Build GUI
            obj.initGUI();
            
            % Initial update
            obj.onModelChanged();
            
            % Observe model changes and update view accordingly
            addlistener(model, 'Dirty', ...
                @obj.onModelChanged);
%             addlistener(model, 'frame', 'PostSet', ...
%                 @obj.onModelChanged);
%             addlistener(model, 'gate', 'PostSet', ...
%                 @obj.onModelChanged);
%             addlistener(model, 'disprange', 'PostSet', ...
%                 @obj.onModelChanged);
%             addlistener(model, 'bidir', 'PostSet', ...
%                 @obj.onModelChanged);
            
        end
        
        function initGUI(obj)
            % Gets the px coordinates delimiting screen area as:
            % Left Bottom Width Height
            scrsz = get(groot,'ScreenSize');
            
            hFig = figure(...
                'Menubar','none', ...
                'Position',[scrsz(3)/4  scrsz(4) / 4 scrsz(3)/2 scrsz(3)/2], ...
                'Name', 'Image', ...
                'NumberTitle', 'off');
            
            % Master panel
            hPanel = uix.Panel('Parent', hFig, ...
                'Padding', 20);
            % Master panel is divided in a 1 column grid with multple lines of
            % controls.
            hGrid = uix.Grid('Parent', hPanel, ...
                'Spacing', 20);
            
            % First the axes.
            hAxes = axes('Parent', uicontainer('Parent', hGrid));
            axis square;
            
            % Next, a row of buttons and labels.
            hBox2 = uix.HBox('Parent', hGrid);
            
            hGridGate = uix.Grid('Parent', hBox2, ...
                'BackgroundColor', 'Green', ...
                'Spacing', 5);
            
            hLblgmin = uicontrol('Parent', hGridGate, ...
                'Style', 'text', ...
                'String', 'Min gate (ns)');
            
            hLblgmax = uicontrol('Parent', hGridGate, ...
                'Style', 'text', ...
                'String', 'Max gate (ns)');
            
            hEdtgmin = uicontrol('Parent', hGridGate, ...
                'Style', 'edit', ...
                'String', '0');
            
            hEdtgmax = uicontrol('Parent', hGridGate, ...
                'Style', 'edit', ...
                'String', '100');
            
            hLblsmin = uicontrol('Parent', hGridGate, ...
                'Style', 'text', ...
                'String', 'Min count (%)');
            
            hLblsmax = uicontrol('Parent', hGridGate, ...
                'Style', 'text', ...
                'String', 'Max count (%)');
            
            hEdtsmin = uicontrol('Parent', hGridGate, ...
                'Style', 'edit', ...
                'String', '0');
            
            hEdtsmax = uicontrol('Parent', hGridGate, ...
                'Style', 'edit', ...
                'String', '100');
            
            hLblbidir = uicontrol('Parent', hGridGate, ...
                'Style', 'text', ...
                'String', 'Bidirectional?');
            
            hChkbidir = uicontrol('Parent', hGridGate, ...
                'Style', 'checkbox', ...
                'Value', 0);
            
            set(hGridGate, 'Widths', [ -1 -1 -1 -1 -1 ], 'Heights', [ -1 -1 ]);
            
            hBox3 = uix.HBox('Parent', hGrid);
            
            set(hGrid, 'Widths', [ -1 ], 'Heights', [ -1 -0.05 -0.05 ]);
            
            hGridNav = uix.Grid('Parent', hBox3, ...
                'Spacing', 5);
            
            hBtndwn = uicontrol('Parent', hGridNav, ...
                'Style', 'pushbutton', ...
                'String', 'Previous');
            
            hEdtfr = uicontrol('Parent', hGridNav, ...
                'Style', 'edit', ...
                'String', '1');
            
            hLblnoframes = uicontrol('Parent', hGridNav, ...
                'Style', 'text', ...
                'String', 'of 0');
            
            hBtnup = uicontrol('Parent', hGridNav, ...
                'Style', 'pushbutton', ...
                'String', 'Next');
            
            set(hGridNav, 'Widths', [ -1 -1 -1 -1 ], 'Heights', [ -1 ]);
            
            obj.handles = struct( ...
                'fig', hFig, ...
                'axes', hAxes, ...
                'edtgmin', hEdtgmin, ...
                'edtgmax', hEdtgmax, ...
                'edtsmin', hEdtsmin, ...
                'edtsmax', hEdtsmax, ...
                'chkbidir', hChkbidir, ...
                'btnup', hBtnup, ...
                'edtfr', hEdtfr, ...
                'lblnoframes', hLblnoframes, ...
                'btndwn', hBtndwn);
            
        end
        
        function onModelChanged(obj, ~, ~)
            image = obj.model.render();
            Min = max(max(image(:))) * obj.model.disprange(1,1) / 100.0;
            Max = max(max(image(:))) * obj.model.disprange(1,2) / 100.0;
            set(obj.handles.fig, 'CurrentAxes', obj.handles.axes);
            imagesc(image, [ Min, Max ]);
            colorbar(obj.handles.axes);
            set(obj.handles.edtfr, 'String', num2str(obj.model.frame));
            set(obj.handles.lblnoframes, 'String', num2str(obj.model.noframes));
        end
        
    end
    
end